// Package db provides Biewer's local, on-disk session history store.
//
// Biewer is local-first: this is plain files under the user's Biewer home
// directory (~/.biewer/sessions/*.json by default plus an events.jsonl
// audit log), never a hosted service. It only stores session lifecycle
// metadata and hook events — no transcripts, no prompts, no tool output.
//
// Storage is intentionally dependency-free (encoding/json + the
// filesystem, no embedded database engine): Biewer's own footprint should
// stay small and boring, and one JSON file per session makes the on-disk
// format directly inspectable with `cat` — fitting for a tool whose whole
// job is transparency into what's running on your machine.
package db

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	"github.com/shaktsin/biewer/internal/model"
)

// StoredSession is a session record plus its persisted peak memory, as
// returned by history queries (`biewer sessions`).
type StoredSession struct {
	model.Session
	PeakMemoryBytes uint64 `json:"peak_memory_bytes"`
}

// DB is a directory-backed store: one JSON file per session under
// <dir>/sessions/, plus an append-only events.jsonl for the hook event
// audit trail.
type DB struct {
	mu     sync.Mutex
	dir    string
	evFile *os.File
}

// Open opens (creating if necessary) the on-disk store rooted at dir
// (typically ~/.biewer).
func Open(dir string) (*DB, error) {
	sessionsDir := filepath.Join(dir, "sessions")
	if err := os.MkdirAll(sessionsDir, 0o755); err != nil {
		return nil, fmt.Errorf("create sessions dir: %w", err)
	}
	f, err := os.OpenFile(filepath.Join(dir, "events.jsonl"), os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return nil, fmt.Errorf("open events log: %w", err)
	}
	return &DB{dir: dir, evFile: f}, nil
}

// Close releases the underlying event log file handle.
func (d *DB) Close() error {
	d.mu.Lock()
	defer d.mu.Unlock()
	return d.evFile.Close()
}

func (d *DB) sessionPath(id string) string {
	// Session IDs are generated by Biewer itself (uuid-like, see cli
	// package) so this is safe from path traversal, but sanitize defensively
	// since it ultimately comes from a hook's environment.
	safe := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
			return r
		default:
			return '_'
		}
	}, id)
	return filepath.Join(d.dir, "sessions", safe+".json")
}

// UpsertSession writes (creating or overwriting) a session's record.
// peakMemoryBytes is merged with any previously recorded peak (max wins) so
// callers don't need read-modify-write races to preserve history.
func (d *DB) UpsertSession(_ context.Context, s model.Session, peakMemoryBytes uint64) error {
	d.mu.Lock()
	defer d.mu.Unlock()

	path := d.sessionPath(s.ID)
	if existing, err := readSessionFile(path); err == nil && existing.PeakMemoryBytes > peakMemoryBytes {
		peakMemoryBytes = existing.PeakMemoryBytes
	}
	rec := StoredSession{Session: s, PeakMemoryBytes: peakMemoryBytes}
	return writeSessionFileAtomic(path, rec)
}

func readSessionFile(path string) (StoredSession, error) {
	var rec StoredSession
	b, err := os.ReadFile(path)
	if err != nil {
		return rec, err
	}
	err = json.Unmarshal(b, &rec)
	return rec, err
}

func writeSessionFileAtomic(path string, rec StoredSession) error {
	b, err := json.MarshalIndent(rec, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal session: %w", err)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, b, 0o644); err != nil {
		return fmt.Errorf("write session file: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename session file: %w", err)
	}
	return nil
}

// RecordEvent appends a hook event to the on-disk audit log.
func (d *DB) RecordEvent(_ context.Context, e model.Event) error {
	d.mu.Lock()
	defer d.mu.Unlock()

	b, err := json.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshal event: %w", err)
	}
	if _, err := d.evFile.Write(append(b, '\n')); err != nil {
		return fmt.Errorf("append event: %w", err)
	}
	return nil
}

// RecentSessions returns up to limit sessions, most recently started first.
func (d *DB) RecentSessions(_ context.Context, limit int) ([]StoredSession, error) {
	entries, err := os.ReadDir(filepath.Join(d.dir, "sessions"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("list sessions dir: %w", err)
	}

	d.mu.Lock()
	defer d.mu.Unlock()

	var out []StoredSession
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		rec, err := readSessionFile(filepath.Join(d.dir, "sessions", e.Name()))
		if err != nil {
			continue // skip unreadable/corrupt files rather than failing the whole listing
		}
		out = append(out, rec)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].StartedAt.After(out[j].StartedAt) })
	if limit > 0 && len(out) > limit {
		out = out[:limit]
	}
	return out, nil
}

// GetSession returns a single session by exact ID or unambiguous ID prefix
// (for `biewer stop <id>` where the user typically pastes a short prefix).
func (d *DB) GetSession(ctx context.Context, idOrPrefix string) (*StoredSession, error) {
	all, err := d.RecentSessions(ctx, 0)
	if err != nil {
		return nil, err
	}
	var match *StoredSession
	for i := range all {
		if all[i].ID == idOrPrefix {
			return &all[i], nil
		}
		if len(idOrPrefix) >= 4 && strings.HasPrefix(all[i].ID, idOrPrefix) {
			if match != nil {
				return nil, fmt.Errorf("session id prefix %q is ambiguous", idOrPrefix)
			}
			m := all[i]
			match = &m
		}
	}
	if match == nil {
		return nil, fmt.Errorf("no session matching %q", idOrPrefix)
	}
	return match, nil
}

// ReadEvents reads back every recorded event for a given session, oldest
// first. Intended for debugging (`biewer sessions --events <id>`), not the
// hot path.
func (d *DB) ReadEvents(sessionID string) ([]model.Event, error) {
	d.mu.Lock()
	path := d.evFile.Name()
	d.mu.Unlock()

	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var out []model.Event
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	for sc.Scan() {
		var e model.Event
		if err := json.Unmarshal(sc.Bytes(), &e); err != nil {
			continue
		}
		if sessionID == "" || e.SessionID == sessionID {
			out = append(out, e)
		}
	}
	return out, sc.Err()
}
